# Build container based on Fedora
FROM fedora:27

RUN dnf -y update && dnf clean all
RUN dnf -y install gcc \
                   git \
                   make \
                   vim \
                   libuuid-devel \
                   openssl-devel \
                   libpciaccess-devel \
                   gnu-efi-devel

WORKDIR /root/acrn

CMD ["/bin/bash"]
